/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module alu(clk, A, B, sel, Y, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output Cout;
  wire Cout;
  output [3:0] Y;
  wire [3:0] Y;
  input clk;
  wire clk;
  input [1:0] sel;
  wire [1:0] sel;
  sky130_fd_sc_hd__buf_1 _44_ (
    .A(sel[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__buf_1 _45_ (
    .A(_02_),
    .X(_01_)
  );
  sky130_fd_sc_hd__or2_2 _46_ (
    .A(B[3]),
    .B(A[3]),
    .X(_03_)
  );
  sky130_fd_sc_hd__inv_2 _47_ (
    .A(sel[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_2 _48_ (
    .A(_04_),
    .B(sel[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_2 _49_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__or2_2 _50_ (
    .A(B[2]),
    .B(A[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor2_2 _51_ (
    .A(B[1]),
    .B(A[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2_2 _52_ (
    .A(B[1]),
    .B(A[1]),
    .X(_09_)
  );
  sky130_fd_sc_hd__a31o_2 _53_ (
    .A1(B[0]),
    .A2(A[0]),
    .A3(_08_),
    .B1(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__and2_2 _54_ (
    .A(B[2]),
    .B(A[2]),
    .X(_11_)
  );
  sky130_fd_sc_hd__a21oi_2 _55_ (
    .A1(_07_),
    .A2(_10_),
    .B1(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2_2 _56_ (
    .A(_06_),
    .B(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_2 _57_ (
    .A(_06_),
    .B(_03_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_2 _58_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2_2 _59_ (
    .A(_15_),
    .B(_07_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__and2b_2 _60_ (
    .A_N(A[0]),
    .B(B[0]),
    .X(_17_)
  );
  sky130_fd_sc_hd__or2b_2 _61_ (
    .A(B[1]),
    .B_N(A[1]),
    .X(_18_)
  );
  sky130_fd_sc_hd__o21ai_2 _62_ (
    .A1(_08_),
    .A2(_17_),
    .B1(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__and2b_2 _63_ (
    .A_N(B[2]),
    .B(A[2]),
    .X(_20_)
  );
  sky130_fd_sc_hd__a21o_2 _64_ (
    .A1(_16_),
    .A2(_19_),
    .B1(_20_),
    .X(_21_)
  );
  sky130_fd_sc_hd__a21oi_2 _65_ (
    .A1(_14_),
    .A2(_21_),
    .B1(_05_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__or2b_2 _66_ (
    .A(B[3]),
    .B_N(A[3]),
    .X(_23_)
  );
  sky130_fd_sc_hd__a32o_2 _67_ (
    .A1(_03_),
    .A2(_05_),
    .A3(_13_),
    .B1(_22_),
    .B2(_23_),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand3_2 _68_ (
    .A(_04_),
    .B(B[0]),
    .C(A[0]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a211o_2 _69_ (
    .A1(B[0]),
    .A2(A[0]),
    .B1(_04_),
    .C1(sel[0]),
    .X(_25_)
  );
  sky130_fd_sc_hd__o211a_2 _70_ (
    .A1(B[0]),
    .A2(A[0]),
    .B1(_24_),
    .C1(_25_),
    .X(Y[0])
  );
  sky130_fd_sc_hd__and3_2 _71_ (
    .A(B[0]),
    .B(A[0]),
    .C(_08_),
    .X(_26_)
  );
  sky130_fd_sc_hd__a21oi_2 _72_ (
    .A1(B[0]),
    .A2(A[0]),
    .B1(_08_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor2_2 _73_ (
    .A(sel[1]),
    .B(sel[0]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__or3b_2 _74_ (
    .A(_26_),
    .B(_27_),
    .C_N(_28_),
    .X(_29_)
  );
  sky130_fd_sc_hd__o21ai_2 _75_ (
    .A1(B[1]),
    .A2(A[1]),
    .B1(sel[0]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nor2_2 _76_ (
    .A(_04_),
    .B(_09_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__xnor2_2 _77_ (
    .A(_08_),
    .B(_17_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__a221o_2 _78_ (
    .A1(_30_),
    .A2(_31_),
    .B1(_32_),
    .B2(_04_),
    .C1(_28_),
    .X(_33_)
  );
  sky130_fd_sc_hd__nand2_2 _79_ (
    .A(_29_),
    .B(_33_),
    .Y(Y[1])
  );
  sky130_fd_sc_hd__xnor2_2 _80_ (
    .A(_16_),
    .B(_19_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nand3_2 _81_ (
    .A(_15_),
    .B(_07_),
    .C(_10_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__or2b_2 _82_ (
    .A(_10_),
    .B_N(_16_),
    .X(_36_)
  );
  sky130_fd_sc_hd__o211a_2 _83_ (
    .A1(sel[0]),
    .A2(_11_),
    .B1(_07_),
    .C1(sel[1]),
    .X(_37_)
  );
  sky130_fd_sc_hd__a31o_2 _84_ (
    .A1(_28_),
    .A2(_35_),
    .A3(_36_),
    .B1(_37_),
    .X(_38_)
  );
  sky130_fd_sc_hd__o21bai_2 _85_ (
    .A1(_05_),
    .A2(_34_),
    .B1_N(_38_),
    .Y(Y[2])
  );
  sky130_fd_sc_hd__a21o_2 _86_ (
    .A1(B[3]),
    .A2(A[3]),
    .B1(sel[0]),
    .X(_39_)
  );
  sky130_fd_sc_hd__or2_2 _87_ (
    .A(_14_),
    .B(_12_),
    .X(_40_)
  );
  sky130_fd_sc_hd__nand2_2 _88_ (
    .A(_14_),
    .B(_12_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__or2_2 _89_ (
    .A(_14_),
    .B(_21_),
    .X(_42_)
  );
  sky130_fd_sc_hd__a32o_2 _90_ (
    .A1(_28_),
    .A2(_40_),
    .A3(_41_),
    .B1(_42_),
    .B2(_22_),
    .X(_43_)
  );
  sky130_fd_sc_hd__a31o_2 _91_ (
    .A1(sel[1]),
    .A2(_03_),
    .A3(_39_),
    .B1(_43_),
    .X(Y[3])
  );
  sky130_fd_sc_hd__dlxtn_1 _92_ (
    .D(_00_),
    .GATE_N(_01_),
    .Q(Cout)
  );
endmodule
